# Generated by Django 3.1.3 on 2020-11-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='tekst',
        ),
    ]
