# Generated by Django 3.1.3 on 2020-11-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app3', '0002_auto_20201129_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tekst',
            new_name='text',
        ),
    ]
